// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjmtxacdjahkbtrmcvfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbXR4YWNkamFoa2J0cm1jdmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDQ1MDksImV4cCI6MjA3MDg4MDUwOX0.MDx-Qjfdd-AIwLPTHWaGnl_6U2_qZOgXDVgoylllVnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});